# Generated by Django 4.2.14 on 2024-07-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0003_productabout_productdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jewellery_store_cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earrings_image', models.ImageField(upload_to='images/')),
                ('rings_image', models.ImageField(upload_to='images/')),
                ('bracelet_image', models.ImageField(upload_to='images/')),
                ('necklace_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
