# Generated by Django 4.2.14 on 2024-07-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0004_jewellery_store_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('featured_product_image', models.ImageField(upload_to='images/')),
                ('featured_product_title', models.CharField(max_length=255)),
                ('featured_product_price', models.CharField(max_length=255)),
            ],
        ),
    ]
