# Generated by Django 4.2.14 on 2024-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0006_instagram_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earrings_image', models.ImageField(upload_to='images/')),
                ('rings_image', models.ImageField(upload_to='images/')),
                ('bracelet_image', models.ImageField(upload_to='images/')),
                ('necklace_image', models.ImageField(upload_to='images/')),
                ('Bangles_image', models.ImageField(upload_to='images/')),
                ('Pendants_image', models.ImageField(upload_to='images/')),
                ('Chain_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
