# Generated by Django 4.2.14 on 2024-07-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0007_categories_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
