# Generated by Django 4.2.14 on 2024-07-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0008_blog_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img_left1', models.ImageField(upload_to='images/')),
                ('slider_img_right1', models.ImageField(upload_to='images/')),
                ('slider_img_left2', models.ImageField(upload_to='images/')),
                ('slider_img_right2', models.ImageField(upload_to='images/')),
                ('slider_img_left3', models.ImageField(upload_to='images/')),
                ('slider_img_right3', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
